const String TEST_BINANCE_API_KEY = 'TEST_BINANCE_API_KEY';
const String TEST_BINANCE_API_SECRET = 'TEST_BINANCE_API_SECRET';

const String TEST_MERCADO_BITCOIN_TAPI_ID = 'TEST_MERCADO_BITCOIN_TAPI_ID';
const String TEST_MERCADO_BITCOIN_TAPI_SECRET = 'TEST_MERCADO_BITCOIN_TAPI_SECRET';

const String ROUTE_ROOT = '/';
const String ROUTE_WATCHING = '/';
const String ROUTE_PORTFOLIO = '/portfolio';
const String ROUTE_PORTFOLIO_DETAILS = '/portfolio/details';
const String ROUTE_SETTINGS = '/settings';

const int ALARM_ID_DEFAULT = 0;
const int ALARM_MIN_USER_ALARMS = 100;
