const TEST_BINANCE_API_KEY = 'TEST_BINANCE_API_KEY';
const TEST_BINANCE_API_SECRET = 'TEST_BINANCE_API_SECRET';

const TEST_MERCADO_BITCOIN_TAPI_ID = 'TEST_MERCADO_BITCOIN_TAPI_ID';
const TEST_MERCADO_BITCOIN_TAPI_SECRET = 'TEST_MERCADO_BITCOIN_TAPI_SECRET';
